### ISSUE TITLE
Add missing methods from flink-streaming-scala

### ISSUE THREAD

**Issue by salvalcantara** [ariskk/flink4s#16]
As stated,

> The lowest hanging fruit would be opening a PR with methods from flink-streaming-scala [...]

@ariskk I don't know if it makes sense to consider all the methods at once, but for now the idea would be to add most (if not all) of them.

**Comment by salvalcantara** [comment]
If you are okay with this @ariskk I might have some time to work on that. BTW, let me know if you want to prioritize certain methods over others.

**Comment by ariskk** [comment]
Hi @salvalcantara , thanks for reaching out!

My approach so far has been to implement methods as I needed them in the various projects I was involved in the last few months.

There are two ways to go here:
	1. Start from the [DataStream](https://github.com/apache/flink/blob/master/flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/DataStream.scala) and port over methods that have not yet been implemented. With tests! 
	2. Implement a wrapper for a new stream type. Eg the [BroadcastConnectedStream](https://github.com/apache/flink/blob/master/flink-streaming-scala/src/main/scala/org/apache/flink/streaming/api/scala/BroadcastConnectedStream.scala)
	3. WindowedStream is the in the middle of the two. It is there, but limited in terms of methods implemented.

Both will work. I suspect (2) is more challenging but more rewarding at the same time. Up to you!

My thinking around this is: at first implement methods with similar(or identical) signatures to `flink-streaming-scala`, so that I can migrate my projects to Scala 3.x without a lot of refactoring. Then as a second step implement new idiomatic Scala APIs.

**Comment by salvalcantara** [comment]
Okay, I will look into 1 and 2 to start with. Thanks!
